CumulusNetworks/ifupdown2

ifupdown/networkinterfaces.py
Hi
Without this fix  You can not use mako namespaces in cumulus 3.1 .
=> fix for passing parameters to templateEngine() class

sbin/start-networking
Checking operstate would require firmware to be loaded and link
negotiation to of taken place. Some firmwares take a few seconds to
upload and online the device, and some link negotiations take a second
or two.
Immediately checking operstate is not feasible here. Checking if the
link is present is a more suitable non-delaying approach.
Signed-off-by: Nigel Kukard <nkukard@lbsd.net>
=> For hotplug devices check if the link is present, not up

addons/batman_adv.py
This series reworks the internal handling of B.A.T.M.A.N. adv. attributes within the addon and adds support for the following new attributes:
* gw-mode (one of { off, client, server })
* multicast-mode (can be 'enabled' or 'disabled')
* distributed-arp-table (cat be 'enabled' or 'disabled')
Example config:
```
pandora:~# ifquery -c bat-foo
iface bat-foo                                         [pass]
batman-ifaces dummy-bat                           [pass]
batman-ifaces-ignore-regex                        [pass]
batman-hop-penalty 7                              [pass]
batman-multicast-mode enabled                     [pass]
batman-distributed-arp-table enabled              [pass]
batman-gw-mode client                             [pass]
```
=> addons: batman_adv: Add support for more B.A.T.M.A.N. adv. attributes.

addons/tunnel.py, ifupdownaddons/iproute2.py
This commit adds support to configure and check gretap tunnels. An example
configuration could look like this:
iface tap0 inet tunnel
mode gretap
local 10.132.255.3
endpoint 10.132.255.1
ttl 64
mtu 1400
tunnel-physdev eth0
#
address 10.10.0.1/2
ifup will happily configure the interface (which it does even without this
patch) and ifquery now can successfully validate the configure interface:
cr03.in.ffho.net:~# ifquery -c tap0
iface tap0 inet tunnel                   [[ OK ]]
tunnel-physdev eth0                  [[ OK ]]
endpoint 10.132.255.1                [[ OK ]]
local 10.132.255.3                   [[ OK ]]
mode gretap                          [[ OK ]]
ttl 64                               [[ OK ]]
mtu 1400                             [[ OK ]]
address 10.10.0.1/24                 [[ OK …
=> addons: tunnel: Add support for GRETAP tunnels.

addons/bridge.py
This simple patch allows the creation of bridges which should be set up
without any ports, like a bridge for virtual machines on a hosting box.
With this patch ifupdown2 get's a step closer to feature parity and
compatiblity with ifupdown1.
=> addons: bridge: allow "bridge-ports: none" for bridges without initial ports.

ifupdown/scheduler.py
Pass the same environment variables to addon scripts from /etc/network/
as are passed to user defined commands in interfaces stanzas. This is
needed for compatibility with ifupdown.
Fixes: #14
=> Pass environment variables to addon scripts

addons/vxlan.py, ifupdown/netlink.py, ifupdownaddons/iproute2.py, nlmanager/nlmanager.py
Add interface configuration option »vxlan-physdev« to set »dev« attribute of VXLAN interfaces and a check for the running configuration.
+
The »vxlan-svcnodeip« corresponds with the multicast »group« parameter of the VXLAN interface and should be checked against this value instead of the »remote« parameter for unicast ptp tunnels.
=> Add support for setting phys-dev for VXLAN interfaces and fix check for vxlan-svcnodeip option.

addons/batman_adv.py
Currently it is called from /usr/sbin/batctl what makes it impossible to use in case one runs a self compiled version for example
=> addon/batctl: lookup batctl dynamically from PATH

ifupdown2/nlmanager/nlpacket.py
This commits fixes AttributeMACAddress for GREv6.
Error message: info: netlink: link dump failed: Length of MACAddress attribute not supported: 20
Reproducible by adding a GREv6 Tunnel:
auto gre1
iface gre1 inet tunnel
mode ip6gre
local 2001:1000:1000:1000::123
endpoint 2001:1000:1000:2000::123
address 192.168.123.1/29
In netlink The IFLA_ADDRESS and IFLA_BROADCAST attributes for all interfaces has been a
6-byte MAC address. But the GRE interface uses a 4-byte IP address and GREv6 uses a 16-byte IPv6 address for this
attribute. This patch allows for decoding a 16-byte value as an IP address.
=> netlink: nlpacket AttributeMACAddress

addons/ethtool.py
This typo breaks get_fec_encoding and seems to force interfaces with fec settings to be reloaded on ifreload -a.
Example from Cumulus Linux 3.6.2:
```
...
info: executing /sbin/ethtool --show-fec swp25
debug: ethtool: problems in ethtool set-fec output ['FEC parameters for swp25:', 'FEC encodings   : None']: local variable 'fec_attrs' referenced before assignment
...
```
Thanks,
Anton
=> Fix indentation error in ethtool.py

addons/tunnel.py, ifupdownaddons/iproute2.py
Create all tunnels - except gretap - with 'ip tunnel', as this supports
most tunnel modes; create gretap tunnels with 'ip link'.
Rework the whole concept of tunnel updates and make sure a tunnel only is
changed - recreated - IFF the configuration has changed. In previos code
'tunnel change' was called on every _up() call. The 'tunnel change' part
was removed completely as it doesn't work on many occations. So IFF the
tunnel related interface configuration has changed, the tunnel is removed
and recreated.
Latest additions added a bunch of new tunnel modes but didn't add support
to read in these modes which breaks 'ifquery' as it falsely marks the mode
as 'fail'.
This addresses Issue #78
=> Tunnel fixes master

addons/tunnel.py, ifupdownaddons/iproute2.py
This is the same as #80 but for the debian-prep2 branch so Debian packets can be easily build with this fix.
Create all tunnels - except gretap - with 'ip tunnel', as this supports
most tunnel modes; create gretap tunnels with 'ip link'.
Rework the whole concept of tunnel updates and make sure a tunnel only is
changed - recreated - IFF the configuration has changed. In previos code
'tunnel change' was called on every _up() call. The 'tunnel change' part
was removed completely as it doesn't work on many occations. So IFF the
tunnel related interface configuration has changed, the tunnel is removed
and recreated.
Latest additions added a bunch of new tunnel modes but didn't add support
to read in these modes which breaks 'ifquery' as it falsely marks the mode
as 'fail'.
This addresses Issue …
=> Tunnel fixes debian prep2

addons/link.py, ifupdown/ifupdownmain.py, ifupdownaddons/iproute2.py
The option »veth-peer-name« forces an veth peer link to be created with
a specific interface name. As the interface name of the "local" part of
the veth link pair already is defined by the name of the interface stanza
this option is added to, now both sides are clearly named.
As there is a bidirectional dependency of both link pairs - both cannot
exist without the other - this presents a problem when setting up all
interfaces. Depending on which interface is set up first there might be
a problem when only on dependency is specified. Therefore adding the
»veth-peer-name« option to both interface of the veth link pair ensures
that regardless of which side is configured first the peer name will be
set correctly. This intentionally creates a circular dependency which is
handled accordingly. …
=> Add option 'veth-peer-name' to veth links and ensure proper configuration

ifupdown2/addons/address.py
classic ifupdown don't change forwarding value if not defined in /etc/network/interfaces (don't even support it).
Currently ifupdown2 behaviour is to turn forwarding off when not defined. (and break sysctl manual enabling (net.ipv4.ip_forward = 1, net.ipv4.conf.all.forwarding = 1, net.ipv4.conf.default.forwarding = 1
on restart or reload).
Better to not change value when not defined, and keep user manual config.
=> don't change interface forwarding value if not defined

etc/network/ifupdown2/addons.conf
Fixes the vrf addon trying to set the master on a tunnel interface, before it has been created.
Example:
```ifupdown2
iface vrf-test inet manual
vrf-table 1001
iface test-tunnel inet tunnel
vrf vrf-test
```
=> ifupdown2addons: fix order of pre-up,vrf and pre-up,tunnel

ifupdown2/addons/batman_adv.py
Add a new attribute for B.A.T.M.A.N. advanced interfaces to control the
B.A.T.M.A.N. advanced routing algorithm to be used when setting up new
interfaces. As the routing algorithm must be set before an interface is
created, it needs special handling and can't be implemented as a common
attribute. D'oh.
Tested-by: Annika Wickert <aw@awlnx.space>
=> addons: batman_adv: Add support to set B.A.T.M.A.N. advanced routing_algo

ifupdown2/ifupdownaddons/modulebase.py
This fix this kind of error:
ifquery -r -a
error: bond0: cmd '/sbin/sysctl net.bridge.bridge-stp-user-space' failed: returned 255 (sysctl: cannot stat /proc/sys/net/bridge/bridge-stp-user-space: No such file or directory
)
error: fwpr103p0: cmd '/sbin/sysctl net.bridge.bridge-stp-user-space' failed: returned 255 (sysctl: cannot stat /proc/sys/net/bridge/bridge-stp-user-space: No such file or directory
)
=> Fix error message on ifquery when sysctl bridge-stp-user-space

etc/network/ifupdown2/addons.conf, ifupdown2/addons/xfrm.py, ifupdown2/ifupdown/netlink.py, ifupdown2/ifupdownaddons/LinkUtils.py, ifupdown2/nlmanager/nlmanager.py, ifupdown2/nlmanager/nlpacket.py
It is available since Kernel 4.19 and has two parameters:
1. XFRM ID to map to an SA/SAs
2. Underlying Interface if you want to take advantage of IPSec Hardware Offload
Otherwise it is treated as a normal interface and not like a tunnel (VTI).
I added two attributes to the interface to configure it and otherwise use it as a normal interface.
One example is:
auto ipsec1
iface ipsec1 inet
xfrm-physdev lo
xfrmid 1
Some useful links are:
https://patchwork.ozlabs.org/patch/924821/
https://wiki.strongswan.org/projects/strongswan/wiki/RouteBasedVPN#XFRM-Interfaces-on-Linux
Best
Sven
=> This commit adds support for the new IPSec Interface XFRM.

ifupdown2/addons/dhcp.py
Add a ifupdown2 policy attribute to allow user to tune the wait time to be
allowed before the dhclient can be started on an IPv6 enabled interface.
=> Policy to wait for IPv6 link local address to be available

debian/changelog, ifupdown2/addons/dhcp.py, ifupdown2/ifupdownaddons/dhclient.py
Add a ifupdown2 policy attribute dhcp6-duid to allow user to specify the DUID type
to be used on an IPv6 enabled interface.
Signed-off-by: Rajendra Dendukuri <rajendra.dendukuri@broadcom.com>
=> addons: dhcp: Policy to specify DUID type to use on dhcpv6 requests

ifupdown2/addons/address.py
Currently, the only way to enable arp-accept is to enable
a policy with l3_intf_arp_accept.
But this enable arp-accept for all bridges.
This option allow to define it for specific bridge.
This is needed with bgp-evpn and vm migration
https://github.com/FRRouting/frr/issues/4904
=> add arp-accept option.

ifupdown2/addons/ethtool.py
Currently GRO, LRO GSO, TSO, UFO, TX and RX Offload are supported.
One can read the current value with ethtool -k NICNAME.
Values are set with ethtool -K NICNAME gro on lro on gso on tso on ufo on tx on rx on
An example for the config file is:
iface eth0 inet static
gro-offload no
The default value will be kept in the statemanager. The default value might differ depending on the NIC and is saved upon the first change.
=> This commit adds the feature to change offloads for nics

ifupdown2/addons/xfrm.py, ifupdown2/lib/iproute2.py, ifupdown2/nlmanager/nlpacket.py
The nlpacket for XFRM had a bug, I also changed iproute2 to add
the XFRM interface to the local cache after creation.
Since XFRM has no IFLA_LINKINFO I made the argument optional.
Otherwise no further operation will be done like adding an IP.
I also removed an unecessary variable in the addon.
Signed-off-by: Sven Auhagen <sven.auhagen@voleatech,de>
=> This patch fixes the XFRM addon for ifupdown2 version 2.

ifupdown2/nlmanager/nlpacket.py
@julienfortin this one is also missing.
=> This also adds ipip6 to nlpacket IFLA_INFO_KIND.

etc/network/ifupdown2/addons.conf, ifupdown2/addons/openvswitch.py, ifupdown2/addons/openvswitch_port.py, ifupdown2/lib/iproute2.py, ifupdown2/nlmanager/nlpacket.py
This is a reimplementation of ifupdown1 script
https://github.com/openvswitch/ovs/blob/master/debian/openvswitch-switch.README.Debian
including reloading support with removal of old options and bridge ports.
The original script is pretty basic, it could be improved a lot later, with adding all properties of devices. (Currently they are simply added in ovs_options && ovs_extra)
=> add openvswitch addons

ifupdown2/addons/bond.py, ifupdown2/nlmanager/nlpacket.py
This option exist in ifupdown1/ifenslave,
used for active-backup bond
=> bond: add bond-primary-reselect option

ifupdown2/addons/openvswitch.py
Like for bridge, add a option to skip delete a regex list of interfaces.
(can be usefull for hypervisor, when vm interfaces are dynamically plugged)
=> addon: openvswitch : add ovs-ports-condone-regex option

ifupdown2/nlmanager/nllistener.py
Currently 4k buffer is too small to handle some netlink messages
(Like bridge vlans for example, with 32k messages detected).
=> nllistener: increase netlink buffer to 64k

ifupdown2/addons/address.py, ifupdown2/addons/openvswitch.py, ifupdown2/addons/openvswitch_port.py, ifupdown2/ifupdown/iface.py
Openvswitch already manage mtu if ovs-mtu is defined.
(Ovs manage mtu in userland, and sync mtu for some interfaces in kernel).
If mtu is changed by address module, before the ovs userland mtu,
this give packets drop.
=> address: don't process_mtu for openvswitch interfaces

ifupdown2/nlmanager/ipnetwork.py
Signed-off-by: Alexandre Bruyelles <abruyelles@odiso.com>
=> nlmanager: fix IPAddress's repr, which must return a str

ifupdown2/addons/vxlan.py
This fixes the incorrect help text for vxlans svcnodeid option
Signed-off-by: Markus Hauschild <markus@moepman.eu>
=> addons: vxlan: fix vxlan-svcnodeip help text

ifupdown2/addons/batman_adv.py
This prevents the error: a bytes-like object is required, not 'str' and fixes #183
Signed-off-by: Markus Hauschild <markus@moepman.eu>
=> addons: batman_adv: use universal_newlines

ifupdown2/addons/bridge.py
User may want to have persistent name of dummy port if "bridge-always-up" option is enabled.
Now the name can be defined in "bridge_always_up_dummy_brport" policy for bridge module.
Signed-off-by: Alexander Petrovskiy <alexpe@nvidia.com>
=> addons: bridge: add support for "bridge_always_up_dummy_brport" policy

ifupdown2/addons/vxlan.py, ifupdown2/lib/iproute2.py, ifupdown2/lib/nlcache.py, ifupdown2/nlmanager/nlmanager.py
Closes #203.
```
auto testvxlan
iface testvxlan
vxlan-id 1947
vxlan-tos 18
vxlan-udp-csum no
```
```
$ sudo python ifreload --all --debug
debug: args = Namespace(all=True, currentlyup=False, CLASS=None, iflist=[], noact=False, verbose=False, debug=True, withdepends=False, perfmode=False, nocache=False, excludepats=None, usecurrentconfig=False, syslog=False, force=False, syntaxcheck=False, version=None, nldebug=False)
debug: creating ifupdown object ..
info: requesting link dump
info: requesting address dump
info: requesting netconf dump
debug: nlcache: reset errorq
debug: {'use_daemon': 'no', 'template_enable': '1', 'template_engine': 'mako', 'template_lookuppath': '/home/spost/Code/ifupdown2/etc/network/ifupdown2/templates', 'default_interfaces_configfile': …
```
=> addons: vxlan: support ToS and udpcsum

ifupdown2/addons/vxlan.py, ifupdown2/ifupdown/ifupdownmain.py
This allows syntax checking to pass for fields like vxlan-ttl/vxlan-tos
which can be a number in a range OR a string value representing a special
meaning (0-255 or "auto", for instance).  Without this, you can only pass
a --syntax-check for such fields if your value is one of those literally
specified because, for instance, "64" is not "auto", "0", or "255":
```
invalid value "64": valid attribute values: ['0', '255']
info: exit status 1
```
Note that _applying_ such configuration still works, because netlink's
acceptance criteria are independent of ifupdown2's.
This should not change behavior for any other type of interface, as none use a `validrange` in combination with a `<number>` keyword.
With this interfaces file:
```
auto testvxlan1
iface testvxlan2
vxlan-local-tunnelip …
```
=> Support value-in-range with <number> keyword

ifupdown2/addons/bridge.py
Readds the `none` value as a valid value for the `bridge-ports` property on a bridge. This was left out in https://github.com/CumulusNetworks/ifupdown2/commit/223ba5af1d4739ca6e1857d9c502e921bb6a3fdd but I couldn't find a reason why.
=> Add none as valid value for bridge-ports on a bridge interface

ifupdown2/addons/tunnel.py
Add `inherit` value for **tunnel-ttl** attribute and also introduce new attribute **tunnel-tos**:
```
'tunnel-tos': {
'help': 'TOS for tunnel packets',
'validvals': ['<number>', 'inherit'],
'required': False,
'example': ['tunnel-tos inherit'],
"aliases": ["tos"]
}
```
These options are required for some HW with tunnel offload support. 
For example, mlxsw switchdev driver:
https://github.com/Mellanox/mlxsw/wiki/L3-Tunneling#features-and-limitations
=> Tunnel tos ttl fix

ifupdown2/addons/bond.py, ifupdown2/nlmanager/nlpacket.py
Add support for xmit-hash-policy 5 - vlan+srcmac, added in Linux 5.12.
=> Update bond.py - add xmit-hash-policy vlan+srcmac

ifupdown2/ifupdown/networkinterfaces.py
This adds sorting when reading files from /etc/network/interfaces.d.  Before this patch, the filenames are returned in random order, which results in some weird behavior.
Consider the following configs:
```
interfaces.d/eno1:
allow-hotplug eno1
auto eno1
iface eno1 inet static
address 10.0.0.130/255.255.255.248
mtu 1500
gateway 10.0.0.129
preferred-lifetime forever
interfaces.d/eno1_55:
iface eno1 inet static
address 10.0.0.131/255.255.255.248
preferred-lifetime 0
```
Since the current code relies on the order from glob.glob (which in turn relies on the order from the filesystem) it's likely that the eno1_55 config file will be parsed first (resulting in the 10.0.0.131 address being the "default" IP on the interface).  ifupdown2 doesn't really have a way for me to tell it to parse eno1 …
=> Sort filenames in interfaces.d so they're parsed in a consistent order

ifupdown2/ifupdown/networkinterfaces.py
This patch series implements support for the `source-directory` statement according to `interfaces(5)`. Additionally relative path handling in `source` and `source-directory` statements is fixed to match the documented behavior:
> When sourcing files or directories, if a path doesn't have a leading slash, it's considered relative to the directory containing the file in which the keyword is placed. In the example above, if the file is located at /etc/network/interfaces, paths to the included files are understood to be under /etc/network.
Excerpt from https://manpages.debian.org/buster/ifupdown/interfaces.5.en.html
Fixes #191
=> networkinterfaces: support source-directory statement

ifupdown2/addons/address.py, ifupdown2/ifupdown/networkinterfaces.py, ifupdown2/lib/nlcache.py, ifupdown2/nlmanager/nlpacket.py
Hi,
This PR tries to resolve the dad issue mentioned in https://github.com/CumulusNetworks/ifupdown2/issues/30.
On debian (tested in bullseye and buster), services such as sshd cannot bind to a static ipv6 right after the networking service, since the defined ipv6 is in a tentative state.
This PR restore some ifupdown (original) handling on DAD.
* adding options to disable dad for an address
* adding a settle dad function to wait for a given time and warn the user in case of the ip could not be validated or timeout.
I understand that ifupdown2 is not meant to be an ifupdown clone in python, so If the default behavior changes are not well receive, we can still discuss changing the configuration attributes or implementation.
=> Dad handling

ifupdown2/addons/address.py, ifupdown2/lib/nlcache.py, ifupdown2/nlmanager/nlpacket.py
Original pull request: https://github.com/CumulusNetworks/ifupdown2/pull/230
This PR tries to resolve the dad issue mentioned in https://github.com/CumulusNetworks/ifupdown2/issues/30.
On debian (tested in bullseye and buster), services such as sshd cannot bind to a static ipv6 right after the networking service, since the defined ipv6 is in a tentative state.
This PR restore some ifupdown (original) handling on DAD.
adding options to disable dad for an address
adding a settle dad function to wait for a given time and warn the user in case of the ip could not be validated or timeout.
I understand that ifupdown2 is not meant to be an ifupdown clone in python, so If the default behavior changes are not well receive, we can still discuss changing the configuration attributes or …
=> Dad handling per itf

debian/ifupdown2.networking.service
In debian 10, ifupdown2 didn't ensure that it will start before network.target and network-online.target.
after local-fs.target because ifupdown2 need to read config file from local filesystem
Other network services will not start after networking.service and fail because no interface is up.
(e.g isc-dhcp-server, tftp-hpa)
In Cumulus, this patch shouldn't be a problem because all switch ports need to be up before starting console for login.
and also need to read config file in local filesystem (need "After=local-fs.target")
=> networking.service: fix start networking.service before network is marked online

ifupdown2/addons/dhcp.py
When a policy dhcp-wait is false the dhcp client is run directly in
background.
But, in most cases, the client won't have the time to find an address
before a check occur.
This is making the client being killed nearly every time.
The obvious solution here is to not check ips differences when no-wait
is asked by the policy.
=> dhcp: fix dhclient client killed on no wait

ifupdown2/addons/bond.py, ifupdown2/lib/sysfs.py, ifupdown2/nlmanager/nlpacket.py
It is only valid for balance-rr and balance-xor.
One Example is:
auto bond0
iface bond0 inet
bond-slaves ens21 ens22
bond-mode balance-rr
bond-arp-interval 100
bond-arp-ip-target 8.8.8.8
address 10.10.10.1/24
Signed-off-by: Sven Auhagen <sven.auhagen@voleatech.de>
=> This patch adds the ability to use an ARP IP for the bond check.

debian/control
gvgen module require the six module from python3-six package.
This new dependency is only necessary for python2/python3 cross
compatibility on dict.iteritems() (py2) vs dict.items() (py3).
ifupdown2 does not support python2 so we could replace every iteritems
occurrences to it's python3 format but this means the gvgen module will
diff from upstream.
The simplest way is to make ifupdown depends on python3-six.
=> gvgen: fix module dependency

ifupdown2/ifupdown/utils.py
If the output of the subprocess is empty, then an empty <bytes> object
is returned (b''), and not decoded into an empty <string> object.
This may result in errors such as:
info[109734]: executing /bin/ip -6 addr show eth0
networking[109734]: error: eth0: cannot use a string pattern on a
bytes-like object
error[109734]: eth0: cannot use a string pattern on a bytes-like object
=> Fix the return value of utils._execute_subprocess

ifupdown2/addons/openvswitch.py
Fake bridge are are ovsbridge child of a parent bridge with a specific vlan tag.
```
auto br-parent
iface br-parent inet manual
ovs_type OVSBridge
auto br-fakev10
iface br-fakev10 inet manual
ovs_type OVSBridge
ovs_bridge br-parent
ovs_options br-parent 10
```
=> addons: openvswitch : add support for fakebridge.

ifupdown2/ifupdown/networkinterfaces.py, ifupdown2/ifupdown/utils.py
This PR is a continuation of: https://github.com/CumulusNetworks/ifupdown2/pull/235.
This will be a series of PRs, and this is Part 1 where only the Python code is affected. The aim is to fix any potential errors or missbehavior (no breaking changes should be present). 
(Part 2 will focus on hotplug/udev handling, and Part 3 will involve reworking and questioning the arguments. Each part should be independent and merge without conflicts with the other two.)
This PR includes the following changes:
* Makes "auto" an alias for "allow-auto" (with the same handling and container).
* Fixes the range for "ifquery/up/down" for "eth[1-2]", bringing only "eth1".
* Clarifies and cleans up some code in "networkinterfaces.py" and "utils.py".
* Improves error handling for the "allow" keyword.
=> fix networkinterfaces processes

ifupdown2/addons/ethtool.py
some nic like mellanox connectx don't work well with vlan aware bridge && rx-vlan-filter.
(They are limited in number of vlans in hardware filtering, and break with big number of vlans like bridge-vids 2-4096)
=> addons: ethtool: add rx-vlan-filter

ifupdown2/ifupdown/scheduler.py
if a script in /etc/network/ifup.d/ is segfaulting,
on config loading (ifup -a), ifupdown2 is stopping
ifup -a
"
info: executing2 /etc/network/if-up.d/postfix
debug: lo: up : running script /etc/network/if-up.d/resolved info: executing2 /etc/network/if-up.d/resolved
error: name 'traceback' is not defined
debug: saving state ..
info: exit status 1
"
with this fix:
debug: lo: up : running script /etc/network/if-up.d/resolved info: executing2 /etc/network/if-up.d/resolved
File "/usr/share/ifupdown2/ifupdown/scheduler.py", line 325, in run_iface_list
cls.run_iface_graph(ifupdownobj, ifacename, ops, parent,
File "/usr/share/ifupdown2/ifupdown/scheduler.py", line 315, in run_iface_graph
cls.run_iface_list_ops(ifupdownobj, ifaceobjs, ops)
File "/usr/share/ifupdown2/ifupdown/scheduler.py", line …
=> scheduler: import traceback

ifupdown2/addons/vxlan.py
In af8d5db22b10909ff06032f1a2acc2f745d1f65b, the transformation of `vnis` (list) to `vnisd` (dictionary) left a reference to `vnis` which is now undefined. We just remove the line as the conversion from range to ints is done earlier in the function.
=> addons: vxlan: fix VNI filter on single VXLAN device

ifupdown2/addons/vxlan.py
fix regression from
https://github.com/CumulusNetworks/ifupdown2/commit/35a4278ffb588ddd9e610f9395853ff35923c069
remote-ips can be None (with evpn for example) but old_remote_ips is an empty list. So the condition is always matching
=> addons: vxlan: fix compare between remote-ips and old_remote_ips

ifupdown2/ifupdown/scheduler.py
Hi,
As mentioned in the commit message, this patch is intended to increase compatibility with ifupdown with regards to how `/etc/network/` scripts are run (see commit message for a simple example).
It also fixes an issue where a Debian 12 host hangs indefinitely on boot if current `ifupdown2` master as well as the packages `ntpsec` and `ntpsec-ntpdate` are installed.
The hang happens because `ntpsec-ntpdate` installs a script [`/etc/network/if-up.d/ntpsec-ntpdate`](https://salsa.debian.org/debian/ntpsec/-/blob/6947b7095b16f6749237cd6240f752b880ba300f/debian/ntpsec-ntpdate.if-up) -- the following excerpt is relevant:
```
#!/bin/sh
...
(
...
service="ntpsec"
...
invoke-rc.d --quiet "$service" start >/dev/null 2>&1 || true
) &
```
The `invoke-rc.d` call amounts to `systemctl start ntpsec`, …
=> scheduler: avoid waiting for stdout eof of /etc/network/ scripts

ifupdown2/addons/address.py
Currently, a bridge always have forward enabled if an ip exist, or disabled if not ip is present.
we can't use ip-forward on|off to override it because of this return.
=> address: allow ip|ip6-forward on bridge

ifupdown2/ifupdown/main.py
Since python 3.2, readfp needs to be replaced by read_file. Python 3.12 dropped the readfp function.
Patch provided as PR by me, as the original reporter failed to do so since 4-4-2024 and my systems break due to this issue.
=> Bug #296: python 3.12 compability

ifupdown2/nlmanager/nlpacket.py
Pretty much as it says on the tin.
It's supported in-kernel now since 5.6 and enables creation of WireGuard interfaces through the `link-type` attribute.
Can then be used to (pre-)create wireguard interfaces like:
```
auto wg-test
iface wg-test inet static
link-type wireguard
address 10.210.0.1/24
mtu 1420
```
=> nlpacket: recognize 'wireguard' as valid IFLA_INFO_KIND value

ifupdown2/ifupdown/iface.py
In ifupdown/iface.py, class ifaceJsonEncoderWithStatus(json.JSONEncoder), in the for-loop, it fails for the IPNetwork objects (keys tunnel-endpoint and tunnel-remote) since they are not of type string. Converting the value(s) to string in the loop resolved it.
```
$ ifquery -c -o json gre1
error: main exception: 'IPNetwork' object has no attribute 'config'
```
Tested with a GRE tunnel, first reported by another user on the Proxmox forum
https://forum.proxmox.com/threads/sdn-tunnel-status-problem.160608/
and reported to the Proxmox bug tracker
https://bugzilla.proxmox.com/show_bug.cgi?id=6078
=> Fix error in ifquery -c -o json <tunnel interface>
