- addons/batman_adv.py
These patches fix some issues with the B.A.T.M.A.N. Adv. addon.
I'd be happy if you would apply them.
Thanks
Max
> Bugfixes for B.A.T.M.A.N. Adv. addon

- addons/address.py
Due to a simple logic bug the 'pointopoint' attribute was ignored when
specifying and address as <ip/mask> and only considered when IP and mask
where given seperately. This commit fixes this behaviour.
When configured in ptp mode »ip addr« will show the IP address without a
netmask which will make »ifquery -c« mark the IP as failed. The check has
been fixed, too.
Signed-off-by: Maximilian Wilhelm <max@rfc2324.org>
> addons: address: Fix handling of 'pointopoint' attr.

- addons/bridge.py
The bridge-ports-condone-regex option can be used to tell ifupdown2 to let
some bridge member ports alone and do not remove them on ifreload runs.
This might come in handy when running a KVM (or any other virtualization
system) host with a bridged network setup.
Before this option, ifupdown2 would either complain about not existing
member ports when setting up the bridge (if all VM interfaces were to
be specified in /etc/network/interfaces) or remove any VM interface
from a bridge if it was not specified in /e/n/i.
Signed-off-by: Maximilian Wilhelm max@rfc2324.org
> Add bridge-ports-condone-regex option.

- addons/tunnel.py
- ifupdownaddons/iproute2.py
Hi,
this allows tunnel attributes to be changed after the initial link creation and also adds more tunnel types like vti and ipv6 tunnels.
Best
Sven
> tunnel changes

- ifupdown2/addons/tunnel.py
This commit fixes the tunnel addon for the new master-next branch.
> addons: tunnel: Add support for master-next

- etc/network/ifupdown2/addons.conf
- ifupdown2/addons/address.py
- ifupdown2/addons/ppp.py
- ifupdown2/ifupdown/networkinterfaces.py
- ifupdown2/ifupdown/scheduler.py
- ifupdown2/ifupdownaddons/LinkUtils.py
This commit fixes the ppp addon for the new master-next branch.
> addons: ppp: Add support for master-next

- ifupdown2/ifupdownaddons/LinkUtils.py
> Fix gretunnels

- addons/address.py
In case of an IPv4 pointopoint setup like the following
auto eth0
iface eth0
address 10.0.0.1/32
pointopoint 10.1.2.3
gateway 10.1.2.3
the configuration would only be correct on the first configuration attemp
by ifupdown2 (read: after systemctl [re]start networking). After any ifup
or ifreload -a the default route would be gone rendering the host offline.
The problem is within an internal comparison between the configured IP on
the interface - read by iproute2 - and the one configured as iproute will
show a pointopoint address without a netmask, but the configuration holds
a /32 mask. This patch will ensure that every address read is represented
in CIDR notation to avoid this issue.
> addons: address: Fix address check for pointopoint setups.

- addons/batman_adv.py
Add a new attribute for B.A.T.M.A.N. advanced interfaces to control the
B.A.T.M.A.N. advanced routing algorithm to be used when setting up new
interfaces. As the routing algorithm must be set before an interface is
created, it needs special handling and can't be implemented as a common
attribute. D'oh.
Tested-by: Annika Wickert <aw@awlnx.space>
> addons: batman_adv: Add support to set B.A.T.M.A.N. advanced routing_algo

- ifupdown2/addons/addressvirtual.py
- ifupdown2/addons/batman_adv.py
- ifupdown2/addons/mstpctl.py
- ifupdown2/ifupdownaddons/LinkUtils.py
This reduce "ifquery -r -a" with 2000vxlans && 2000 bridges, from 8min to 25s.
(In the 25s, around 10s is take by netlink to retrieve linkinfo)
> Fix ifquery speed

- ifupdown2/addons/tunnel.py
Just saw in the diff of your compatibility glue - thanks for that! - that the examples don't reflect the new names :-)
> addons: tunnel: Update examples to new attr names (#133)

- debian/control
Signed-off-by: bauen1 <j2468h@gmail.com>
> add missing build dependency

- ifupdown2/addons/batman_adv.py
Trying to cleanup batman_adv:
* Reformatting code according to PEP8 - it overflows with superfuous whitespace and indentation that is not a multiple of four
* Fixed unresolved reference `netlink`
> Cleanup batman adv

- ifupdown2/addons/address.py
@aderumier can you please try this out and let me know if that fixes your issue?
> addons: bridge: enable forwarding on dhcp bridges (fixes: #179)

- ifupdown2/addons/usercmds.py
- ifupdown2/ifupdown/utils.py
The original ifupdown sets all interface options as IF_<option> environment
variable. Duplicate that behavior for compatibility.
> addons: usercmds: Set environment just like the original ifupdown

- ifupdown2/addons/bond.py
Signed-off-by: Danny Abukalam <danny@softiron.com>
> Correct typo in bond-slaves regex example

- ifupdown2/ifupdown/iface.py
Corrected a typo when the interface is set to KEEP_LINK_DOWN
> Update iface.py : Corrected a typo when the interface is set to KEEP_LINK_DOWN

- ifupdown2/addons/address.py
- ifupdown2/ifupdown/networkinterfaces.py
- ifupdown2/lib/nlcache.py
- ifupdown2/nlmanager/nlpacket.py
Reverts CumulusNetworks/ifupdown2#230
> Revert "Dad handling"

- ifupdown2/addons/bond.py
adding correct support for multiple ip in bond-arp-ip-target
Signed-off-by: Sven Auhagen <sven.auhagen@voleatech.de>
> addons: bond: fix ifquery for IFLA_BOND_ARP_IP_TARGET

- ifupdown2/addons/ethtool.py
example:
```
auto eth0
iface eth0 inet dhcp
ring-tx 1024
ring-rx 1024
```
Signed-off-by: Tomas Vilemaitis
> addons: Add `--set-ring` option to ethtool

- ifupdown2/addons/vlan.py
/etc/network/interfaces
-----------------------
auto eth0.100
iface eth0.100
vlan-protocol 802.1ad
current
-------
ifquery -a -c
auto eth0.100
iface eth0.100                                                      [pass]
new
---
ifquery -a -c
auto eth0.100
iface eth0.100                                                      [pass]
vlan-protocol 802.1ad                                  [pass]
> vlan: query_check: check vlan-protocol for not dotted interface

- ifupdown2/addons/ethtool.py
This makes some automation cases much easier
```
auto eth0
iface eth0 inet dhcp
ring-rx max
ring-tx max
Ring parameters for eth0:
Pre-set maximums:
RX:		4096
RX Mini:	n/a
RX Jumbo:	n/a
TX:		4096
Current hardware settings:
RX:		4096
RX Mini:	n/a
RX Jumbo:	n/a
TX:		4096
```
> addons: Allow to set `max` value in `--set-ring` option
